spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.42.134:3309/master
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.42.134:3308/master
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://192.168.42.134:3305/master
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver